Added update company/employee and delete employee from company
AsuSoftware/My-Trasporter-Back-end pull request #7
Opened 2020-12-30 15:03 UTC by AsuSoftware

Am adaugat ce mi-ai cerut, plus delete employee din companie. Sper sa fie totul ok. Astept code review

2020-12-30 18:24 UTC, icatalin201 requested changes

2020-12-30 18:24 UTC, icatalin201 commented on src/main/java/com/asusoftware/transporter/controller/CompanyController.java
> +  @PutMapping(path = "/remove/employee")
una vorbim alta facem... parca am zis ca sa folosesti verbe in path nu se practica in REST :))
de ce nu faci un DELETE pe /api/v1/employees/id?

2020-12-30 18:24 UTC, icatalin201 commented on src/main/java/com/asusoftware/transporter/service/impl/CompanyServiceImpl.java
> +    Company company = companyRepository.findById(companyId).orElseThrow(CompanyNotFoundException::new);
nu poti sa apelezi metoda de findById? trebuie sa scrii iar acelasi lucru?

2020-12-30 18:24 UTC, icatalin201 commented on src/main/java/com/asusoftware/transporter/service/impl/CompanyServiceImpl.java
> +  public void removeEmployee(RemoveEmployeeDto removeEmployeeDto) {
nu are ce cauta aici... se face pe employee service

2020-12-30 18:24 UTC, icatalin201 commented on src/main/java/com/asusoftware/transporter/service/impl/EmployeeServiceImpl.java
> +    Employee employee = employeeRepository.findById(employeeId).orElseThrow(EmployeeNotFoundException::new);
din nou.... nu poti sa folosesti findById ce exista deja? crezi ca daca te grabesti sa faci repede dovedesti ceva...?

2020-12-30 18:24 UTC, icatalin201 commented on src/main/java/com/asusoftware/transporter/service/impl/EmployeeServiceImpl.java
> +    employee.setCompany(companyService.findById(updateEmployeeDto.getCompanyId()));
cand actualizezi un angajat nu ar trebui sa ii schimbi compania :))) wtf adica gandeste-te putin, intru sa imi actualizez profilul, si ce sa vezi, pot sa imi schimb si compania :)))))

2020-12-31 10:30 UTC, AsuSoftware commented on src/main/java/com/asusoftware/transporter/service/impl/CompanyServiceImpl.java
> +    Company company = companyRepository.findById(companyId).orElseThrow(CompanyNotFoundException::new);
Cum adica? Aici caut compania prin id-ul ei, fac findById ca sa o gasesc

2020-12-31 10:57 UTC, icatalin201 requested changes

2020-12-31 10:57 UTC, icatalin201 commented on src/main/java/com/asusoftware/transporter/controller/EmployeeController.java
> +    employeeService.removeEmployee(removeEmployeeDto);
nu e redundant sa fii pe EmployeeController si EmployeeService si metoda sa se numeasca removeEmployee? daca sunt deja pe employee ce pot sa sterg, un table? normal ca un employee

2020-12-31 10:57 UTC, icatalin201 commented on src/main/java/com/asusoftware/transporter/controller/ParcelController.java
> +  public void createParcel(@RequestBody CreateParcelDto createParcelDto) {
la fel redundant createParcel

2020-12-31 10:57 UTC, icatalin201 commented on src/main/java/com/asusoftware/transporter/service/CompanyService.java
> +  void update(UUID companyId, UpdateCompanyDto updateCompanyDto);
companyId, iar redundant

2020-12-31 10:57 UTC, icatalin201 commented on src/main/java/com/asusoftware/transporter/service/EmployeeService.java
> +  void update(UUID employeeId, UpdateEmployeeDto updateEmployeeDto);
employeeId, redundant

2020-12-31 10:57 UTC, icatalin201 commented on src/main/java/com/asusoftware/transporter/controller/EmployeeController.java
> +    employeeService.removeEmployee(removeEmployeeDto);
si pe langa asta, gandesti ce faci? trimiti un request body pe DELETE ? de ce? si de ce nu ai mapat id-ul din path?

2020-12-31 10:57 UTC, icatalin201 commented on src/main/java/com/asusoftware/transporter/service/EmployeeService.java
> +  void removeEmployee(RemoveEmployeeDto removeEmployeeDto);
nu ai nevoie de un dto pentru delete

2020-12-31 10:57 UTC, icatalin201 commented on src/main/java/com/asusoftware/transporter/service/impl/EmployeeServiceImpl.java
> +    Employee employee = employeeRepository.findById(employeeId).orElseThrow(EmployeeNotFoundException::new);
pai unde apelezi metoda findById ca eu vad ca tot asa e scris, acelasi lucru :))

2020-12-31 10:57 UTC, icatalin201 commented on src/main/java/com/asusoftware/transporter/service/impl/EmployeeServiceImpl.java
> +    if (employee.getCompany().equals(company)) {
o logica in plus si inutila... de ce am nevoie sa stiu si compania daca eu doar sterg angajatul?

2020-12-31 12:03 UTC, icatalin201 approved these changes

2020-12-31 14:06 UTC, merged